version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/docker-image/tp/TP_nodejs/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
  AfterInstall:
    - location: scripts/execute-deploy.sh
      timeout: 180