version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/docker-image/tp/TP_nodejs/
    
permissions:
  - object: /
    pattern: "**"
    mode: 775
    type:
      - file

hooks:
  BeforeInstall:
    - location: beforeInstall.sh
      timeout: 60

  AfterInstall:
    - location: execute-deploy.sh
      timeout: 60
