version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/docker-image/tp/TP_nodejs/
    overwrite: true
    
permissions:
  - object: /
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 775

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 60
  AfterInstall:
    - location: scripts/execute-deploy.sh
      timeout: 180